# Generated by Django 4.0.4 on 2022-10-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('monthly_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('yearly_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('video_quality', models.CharField(max_length=250, null=True)),
                ('resolution', models.CharField(max_length=250, null=True)),
                ('devices', models.ManyToManyField(related_name='plans', to='subscription.device')),
            ],
        ),
    ]
