# Generated by Django 4.0.4 on 2022-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='screens',
            field=models.IntegerField(default=0),
        ),
    ]
