# Generated by Django 4.0.4 on 2022-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_rename_price_id_plan_monthly_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_price_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='yearly_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='yearly_price_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='membership',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
