# Generated by Django 4.0.4 on 2022-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_plan_monthly_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='membership',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
